### PR TITLE
Reorganize tests so that the functional tests are also discovered and run

### PR DESCRIPTION
**Pull request by gyst**
WIP

### CODE REVIEW

**Comment by janwijbrand** [comment]
The test failure under pypy seems, maybe, to be related to how the security proxy should allow access to the `__unicode__` attribute; this is apparently allowed in py27.

**Comment by jamadden** [comment]
> The test failure under pypy seems, maybe, to be related to how the security proxy should allow access to the `__unicode__` attribute; this is apparently allowed in py27.

I would expect `__unicode__` to be handled for pure-Python (as well as C) security proxies given zope.proxy 4.1.5 or newer. See https://github.com/zopefoundation/zope.security/issues/10

**Comment by jamadden** [comment]
> I would expect __unicode__ to be handled for pure-Python (as well as C) security proxies given zope.proxy 4.1.5 or newer.

I would expect that, but I would be **wrong**. The example test now fails:

```pycon
In [10]: type(prox)
Out[10]: zope.security.proxy.ProxyPy

In [11]: unicode(prox)
---------------------------------------------------------------------------
ForbiddenAttribute                        Traceback (most recent call last)
<ipython-input-11-cb9aea809750> in <module>()
----> 1 unicode(prox)

//src/zope/security/proxy.pyc in _wrapper(self, *args, **kw)
     30         wrapped = super(PyProxyBase, self).__getattribute__('_wrapped')
     31         checker = super(PyProxyBase, self).__getattribute__('_checker')
---> 32         checker.check(wrapped, name)
     33         res = meth(self, *args, **kw)
     34         if not wrap_result:

//src/zope/security/checker.pyc in check(self, object, name)
    266         if name != '__iter__' or hasattr(object, name):
    267             __traceback_supplement__ = (TracebackSupplement, object)
--> 268             raise ForbiddenAttribute(name, object)
    269
    270     check_getattr = check # 'See IChecker'

ForbiddenAttribute: ('__unicode__', <__main__.CustomClass object at 0x10b6dd110>)
```

I'll take a look.

**Comment by janwijbrand** [comment]
Thanks for your comment/assistance @jamadden !

**Comment by jamadden** [comment]
The PyPy issues should be fixed by https://github.com/zopefoundation/zope.security/pull/52

**Comment by jamadden** [comment]
zope.security 4.2.2 has been released with the fix.

**Comment by gyst** [comment]
The pin here can be removed once https://github.com/zopefoundation/groktoolkit/pull/6 is merged.

**Comment by janwijbrand** [comment]
Thanks @jamadden for picking up the `zope.security` issue. It helps us out tremendously!

**Review by janwijbrand — APPROVED** [review]

**Pull request merged**
